apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calibre
resources:
  - calibre-container-env-secret.yaml
  - cloudflared-configmap.yaml
  - cloudflared-deployment.yaml
  - cloudflared-creds-secret.yaml
  - ../../base/calibre/
