apiVersion: v1
kind: Service
metadata:
  name: calibre
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: "web"
    - protocol: TCP
      port: 81
      targetPort: 8081
      name: "server"
  selector:
    app: calibre
  type: ClusterIP
