apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  config.yaml: |
    tunnel: kavita
    credentials-file: /etc/cloudflared/creds/credentials.json

    no-autoupdate: true
    ingress:
    - hostname: kavita.eniohomelab.com
      service: http://kavita:80
    - service: http_status:404
