apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kavita
resources:
  - cloudflared-configmap.yaml
  - cloudflared-deployment.yaml
  - cloudflared-creds-secret.yaml
  - ../../base/kavita/
